name: .NET Core Desktop

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: AppControleMantec.sln
      Test_Project_Path: AppControleMantec.Domain.Test/AppControleMantec.Domain.Test.csproj
      SERVER_DIR: 'C:/inetpub/wwwroot/AppControleMantec_Back'
      SERVER_IP: '192.168.0.4'
      SERVER_USER: 'Administrator'

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Restore the app
      run: msbuild ${{ env.Solution_Name }} /t:Restore /p:Configuration=${{ matrix.configuration }}

    - name: Build the app
      run: msbuild ${{ env.Solution_Name }} /p:Configuration=${{ matrix.configuration }}

    - name: Run unit tests
      run: dotnet test ${{ env.Test_Project_Path }} /p:Configuration=${{ matrix.configuration }}

    - name: Archive Build Artifacts (Bin)
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts-bin-${{ matrix.configuration }}
        path: '**/bin/${{ matrix.configuration }}/'
        if-no-files-found: warn

    - name: Archive Build Artifacts (Obj)
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts-obj-${{ matrix.configuration }}
        path: '**/obj/${{ matrix.configuration }}/'
        if-no-files-found: warn

    - name: Deploy to Server
      if: github.ref == 'refs/heads/main'  # Deploy apenas no branch main
      run: |
        echo "***" > private_key
        chmod 600 private_key
        destination="${env:SERVER_USER}@${env:SERVER_IP}:${env:SERVER_DIR}"
        scp -i private_key -r **/bin/${{ matrix.configuration }}/* $destination
        scp -i private_key -r **/obj/${{ matrix.configuration }}/* $destination
        rm private_key
      shell: pwsh
