name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: AppControleMantec.sln
      Test_Project_Path: AppControleMantec.Domain.Test/AppControleMantec.Domain.Test.csproj
      Server_IP: 192.168.0.4
      Server_User: SeuUsuario
      Server_Dir: C:/inetpub/wwwroot/AppControleMantec_Back  # Alterado para o caminho do seu backend

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore the app
        run: msbuild ${{ env.Solution_Name }} /t:Restore /p:Configuration=${{ matrix.configuration }}

      - name: Build the app
        run: msbuild ${{ env.Solution_Name }} /p:Configuration=${{ matrix.configuration }}

      - name: Run unit tests
        run: dotnet test ${{ env.Test_Project_Path }} /p:Configuration=${{ matrix.configuration }}

      - name: Archive Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: |
            **/bin/${{ matrix.configuration }}/
            **/obj/${{ matrix.configuration }}/

      - name: Transfer Files to Remote Server
        run: |
          echo "put -r **/bin/${{ matrix.configuration }}/ **/obj/${{ matrix.configuration }}/" > upload_script.txt
          echo "exit" >> upload_script.txt
          type upload_script.txt | pscp -l Administrator -P 22 -pw Abacate+Verde -batch -bc upload_script.txt SeuUsuario@192.168.0.4:${{ env.Server_Dir }}
        shell: bash
