name: .NET Core Desktop

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: AppControleMantec.sln
      Test_Project_Path: AppControleMantec.Domain.Test/AppControleMantec.Domain.Test.csproj
      Server_Dir: C:/inetpub/wwwroot/AppControleMantec_Back  # Caminho para o backend no servidor

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install .NET Core SDK
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '8.0.32'

      - name: Restore Dependencies
        run: dotnet restore ${{ env.Solution_Name }}

      - name: Build the Project
        run: dotnet build ${{ env.Solution_Name }} --configuration ${{ matrix.configuration }}

      - name: Run Unit Tests
        run: dotnet test ${{ env.Test_Project_Path }} --configuration ${{ matrix.configuration }}

      - name: Publish Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: |
            **/bin/${{ matrix.configuration }}/
            **/obj/${{ matrix.configuration }}/

      - name: Deploy to Server
        if: github.ref == 'refs/heads/main'  # Deploy apenas no branch main
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
          chmod 600 private_key
          scp -i private_key -r **/bin/${{ matrix.configuration }}/* **/obj/${{ matrix.configuration }}/* ${{ secrets.Server_User }}@${{ secrets.Server_IP }}:${{ env.Server_Dir }}
          rm private_key
